from .file_summary_template import (
    FILE_SUMMARY_TEMPLATE,
    CODEBASE_SUMMARY_TEMPLATE, 
    ARCHITECTURAL_INSIGHTS_TEMPLATE,
    CODE_QUALITY_TEMPLATE
)

__all__ = [
    'FILE_SUMMARY_TEMPLATE',
    'CODEBASE_SUMMARY_TEMPLATE',
    'ARCHITECTURAL_INSIGHTS_TEMPLATE', 
    'CODE_QUALITY_TEMPLATE'
]

